// Generated by CoffeeScript 1.12.4
(function() {
  $('form').submit(function(e) {
    window.location.pathname = $('input').val();
    e.preventDefault();
    return false;
  });

}).call(this);

//# sourceMappingURL=script.js.map
